### ISSUE TITLE
Make some changes in looks (no programming)!

### ISSUE THREAD

**Issue by EdgeKing810** [kinesissociety/kinesissociety.github.io#1]
Change as many icons as you want or even the background image as long as there is no copyright issues or make your own. Make sure changes are consistent with other elements of the website. 

>For beginners:
 >   * Fork this repo.
 >   * Clone **your** forked repo and make the required changes.
 >   * Can be previewed how the final page will look by opening ``index.html`` in a web browser.
 >   * Search about and submit a Pull Request!

**Comment by DilkiSasikala** [comment]
I want to attempt this one.

**Comment by grvkmrpandit** [comment]
changing icons

**Comment by Sweta271097** [comment]
@EdgeKing810 Can I work on this or is it already issue to someone else?

**Comment by EdgeKing810** [comment]
Damn, well first one who did it well then '-'

**Comment by EdgeKing810** [comment]
@DilkiSasikala I'm approving the changes you made. For @Sweta271097 and @grvkmrpandit, I'll be opening similar issues in other repos. Be sure to tackle them first tho! Will comment down further for new issues.

**Comment by EdgeKing810** [comment]
Here y'all go!
https://github.com/kinesisgamesblog/kinesisgamesblog.github.io/issues
https://github.com/kinesisdownloads/kinesisdownloads.github.io/issues
https://github.com/kinesisos/kinesisos.github.io/issues
